<?php

declare(strict_types=1);

namespace MageOS\Blog\Test\Integration\Model\Url;

use Magento\Framework\App\ResourceConnection;
use Magento\TestFramework\Helper\Bootstrap;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use MageOS\Blog\Api\Data\AuthorInterfaceFactory;
use MageOS\Blog\Api\Data\CategoryInterfaceFactory;
use MageOS\Blog\Api\Data\PostInterface;
use MageOS\Blog\Api\Data\PostInterfaceFactory;
use MageOS\Blog\Api\Data\TagInterfaceFactory;
use MageOS\Blog\Model\Url\UrlRewriteBuilder;
use PHPUnit\Framework\TestCase;

/**
 * The builder takes the generated UrlRewriteFactory, so it is covered here rather than in Test/Unit.
 *
 * @magentoAppArea adminhtml
 * @magentoDbIsolation enabled
 * @magentoAppIsolation enabled
 */
final class UrlRewriteBuilderTest extends TestCase
{
    public function test_explicit_store_ids_are_kept(): void
    {
        $rows = $this->builder()->buildForPost($this->post(), [1]);

        self::assertCount(1, $rows);
        self::assertSame([1], $this->storeIdsOf($rows));
        self::assertSame(UrlRewriteBuilder::ENTITY_TYPE_POST, $rows[0]->getEntityType());
        self::assertSame(7, (int) $rows[0]->getEntityId());
        self::assertSame('blog/builder-post', $rows[0]->getRequestPath());
        self::assertSame('blog/post/view/id/7', $rows[0]->getTargetPath());
        self::assertSame(0, (int) $rows[0]->getRedirectType());
        self::assertSame(1, (int) $rows[0]->getIsAutogenerated());
    }

    public function test_duplicate_store_ids_produce_one_row(): void
    {
        $rows = $this->builder()->buildForPost($this->post(), [1, 1]);

        self::assertSame([1], $this->storeIdsOf($rows));
    }

    /**
     * @magentoDataFixture Magento/Store/_files/store.php
     */
    public function test_all_store_views_expands_to_every_store(): void
    {
        $expected = $this->everyStoreId();
        self::assertGreaterThan(1, \count($expected), 'The store fixture should add a second store.');

        $rows = $this->builder()->buildForPost($this->post(), [0]);

        self::assertSame($expected, $this->storeIdsOf($rows));
        self::assertNotContains(0, $this->storeIdsOf($rows), 'Store 0 is a marker, not a rewrite target.');
    }

    /**
     * Regression: an empty store list used to make the plugins skip rewrite generation entirely.
     *
     * @magentoDataFixture Magento/Store/_files/store.php
     */
    public function test_missing_assignment_expands_to_every_store(): void
    {
        $rows = $this->builder()->buildForPost($this->post(), []);

        self::assertSame($this->everyStoreId(), $this->storeIdsOf($rows));
    }

    /**
     * @magentoDataFixture Magento/Store/_files/store.php
     */
    public function test_zero_alongside_a_store_still_expands_to_every_store(): void
    {
        $rows = $this->builder()->buildForPost($this->post(), [0, 1]);

        self::assertSame($this->everyStoreId(), $this->storeIdsOf($rows));
    }

    public function test_category_rewrites_use_the_category_path(): void
    {
        $category = Bootstrap::getObjectManager()->get(CategoryInterfaceFactory::class)->create();
        $category->setCategoryId(4)->setUrlKey('builder-category');

        $rows = $this->builder()->buildForCategory($category, [1]);

        self::assertCount(1, $rows);
        self::assertSame(UrlRewriteBuilder::ENTITY_TYPE_CATEGORY, $rows[0]->getEntityType());
        self::assertSame('blog/category/builder-category', $rows[0]->getRequestPath());
        self::assertSame('blog/category/view/id/4', $rows[0]->getTargetPath());
    }

    public function test_tag_rewrites_use_the_tag_path(): void
    {
        $tag = Bootstrap::getObjectManager()->get(TagInterfaceFactory::class)->create();
        $tag->setTagId(9)->setUrlKey('builder-tag');

        $rows = $this->builder()->buildForTag($tag, [1]);

        self::assertCount(1, $rows);
        self::assertSame(UrlRewriteBuilder::ENTITY_TYPE_TAG, $rows[0]->getEntityType());
        self::assertSame('blog/tag/builder-tag', $rows[0]->getRequestPath());
        self::assertSame('blog/tag/view/id/9', $rows[0]->getTargetPath());
    }

    /**
     * Author has no store pivot, so it always covers every store.
     *
     * @magentoDataFixture Magento/Store/_files/store.php
     */
    public function test_author_rewrites_cover_every_store(): void
    {
        $author = Bootstrap::getObjectManager()->get(AuthorInterfaceFactory::class)->create();
        $author->setAuthorId(2)->setSlug('builder-author');

        $rows = $this->builder()->buildForAuthor($author);

        self::assertSame($this->everyStoreId(), $this->storeIdsOf($rows));
        self::assertSame(UrlRewriteBuilder::ENTITY_TYPE_AUTHOR, $rows[0]->getEntityType());
        self::assertSame('blog/author/builder-author', $rows[0]->getRequestPath());
        self::assertSame('blog/author/view/id/2', $rows[0]->getTargetPath());
    }

    private function post(): PostInterface
    {
        $post = Bootstrap::getObjectManager()->get(PostInterfaceFactory::class)->create();

        return $post->setPostId(7)->setUrlKey('builder-post');
    }

    private function builder(): UrlRewriteBuilder
    {
        return Bootstrap::getObjectManager()->create(UrlRewriteBuilder::class);
    }

    /**
     * Read the stores straight from the table so the expectation does not come from StoreManager,
     * which is what the builder itself uses.
     *
     * @return int[]
     */
    private function everyStoreId(): array
    {
        $resource = Bootstrap::getObjectManager()->get(ResourceConnection::class);
        $connection = $resource->getConnection();

        $ids = array_map('intval', $connection->fetchCol(
            $connection->select()
                ->from($resource->getTableName('store'), ['store_id'])
                ->where('store_id > ?', 0)
        ));
        sort($ids);

        return $ids;
    }

    /**
     * @param UrlRewrite[] $rows
     *
     * @return int[]
     */
    private function storeIdsOf(array $rows): array
    {
        $ids = array_map(static fn (UrlRewrite $row): int => (int) $row->getStoreId(), $rows);
        sort($ids);

        return $ids;
    }
}
